# Generated by Django 6.0 on 2025-12-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "ordering": ["email"],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                help_text="Обязательное поле. Уникальный email адрес.",
                max_length=254,
                unique=True,
                verbose_name="Email",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_manager",
            field=models.BooleanField(
                default=False,
                help_text="Отметьте, если пользователь является менеджером",
                verbose_name="Менеджер",
            ),
        ),
    ]
